from fastapi import FastAPI, HTTPException, File, UploadFile, Form, Depends
from sqlalchemy import create_engine, text
from app.schemas import PostResponse
from app.db import Post, create_db_and_tables, get_async_session
from sqlalchemy.ext.asyncio import AsyncSession
from contextlib import asynccontextmanager
from sqlalchemy import select
from app.images import imagekit
from imagekitio.models.UploadFileRequestOptions import UploadFileRequestOptions
import shutil
import os
import uuid
import tempfile






# This decorator allows us to define async startup and shutdown logic
@asynccontextmanager
async def lifespan(app: FastAPI):
    # Runs once when the FastAPI app starts
    # Ensures database tables are created before handling requests
    await create_db_and_tables()
    
    # Pauses here and hands control back to FastAPI
    # The app runs while execution is "inside" this context
    yield
    # (Optional) cleanup code would go here on shutdown


# Create the FastAPI application instance
# The lifespan function is registered to handle startup/shutdown events
app = FastAPI(lifespan=lifespan)



# Define a POST endpoint at /upload
# This endpoint is responsible for creating a new Post entry
@app.post("/upload")
async def upload_file(
    # Accepts a required uploaded file from a multipart/form-data request
    file: UploadFile = File(...),
    
    # Accepts an optional text field from the same form request
    # Defaults to an empty string if not provided
    caption: str = Form(""),
    
    # Injects an async database session using FastAPI's dependency system
    session: AsyncSession = Depends(get_async_session)
):

    temp_file_path = None


    try:
        with tempfile.NamedTemporaryFile(delete=False, suffix=os.path.splittext(file.filename)[1]) as temp_file:
            temp_file_path = temp_file.name 
            shutil.copyfileobj(file.file, temp_file)

        upload_result = imagekit.upload_file(
            file=open(temp_file_path, "rb"),
            file_name=file.filename,
            options=UploadFileRequestOptions(
                use_unique_file_name=True,
                tags=["backend-upload"]
            )
        )

        if upload_result.resonse.http_status_code == 200:

            # Create a new Post ORM object (not yet saved to the database)
            post = Post(
                caption=caption,        # Text caption provided by the user
                url=upload_result.url,        # Placeholder for where the file would be stored
                file_type="video" if file.content_type.startswith("video/") else "image",      # Hardcoded file type for now
                file_name=upload_result.name  # Placeholder file name
            )

            # Stage the Post object for insertion into the database
            session.add(post)
            
            # Commit the transaction (actually writes the record to the DB)
            await session.commit()
            
            # Refresh the object so autogenerated fields (id, created_at) are loaded
            await session.refresh(post)
            
            # Return the newly created Post object as the API response
            return post
    except Exception as e:
        raise HTTPException(status_code=500, details=str(e))
    finally:
        if temp_file_path and os.path.exists(temp_file_path):
            os.unlink(temp_file_path)
        file.file.close()





# Define a GET endpoint at /feed
# This endpoint retrieves a list of posts ordered by newest first
@app.get("/feed")
async def get_feed(
    # Inject an async database session
    session: AsyncSession = Depends(get_async_session)
): 
    # Execute a SELECT query to fetch all Post records
    # Results are ordered by creation time in descending order
    result = await session.execute(
        select(Post).order_by(Post.created_at.desc())
    )
    
    # Extract Post objects from the SQLAlchemy result rows
    posts = [row[0] for row in result.all()]


    # Prepare a list to hold JSON-serializable post data
    posts_data = []
    
    # Loop through each Post ORM object
    for post in posts:
        posts_data.append(
            {
                # Convert UUID to string for JSON compatibility
                "id": str(post.id),
                
                # Caption text
                "caption": post.caption,
                
                # URL pointing to the uploaded file
                "url": post.url,
                
                # Type of file (e.g., photo, video)
                "file_type": post.file_type,
                
                # Original file name
                "file_name": post.file_name,
                
                # Convert datetime to ISO 8601 string for APIs
                "created_at": post.created_at.isoformat()
            }
        )

    # Return the list of posts wrapped in a dictionary
    return {"posts": posts_data}
